/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stringnative_StringNative */

#ifndef _Included_stringnative_StringNative
#define _Included_stringnative_StringNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stringnative_StringNative
 * Method:    println
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_stringnative_StringNative_println__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     stringnative_StringNative
 * Method:    println
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stringnative_StringNative_println__
  (JNIEnv *, jclass);

/*
 * Class:     stringnative_StringNative
 * Method:    println
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_stringnative_StringNative_println__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
