/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testNative_testNative */

#ifndef _Included_testNative_testNative
#define _Included_testNative_testNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testNative_testNative
 * Method:    callingSystem
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_testNative_testNative_callingSystem
  (JNIEnv *, jclass);

/*
 * Class:     testNative_testNative
 * Method:    CallingSystem
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_testNative_testNative_CallingSystem
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
