/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unstatifiedlink_Unstatifiedlink */

#ifndef _Included_unstatifiedlink_Unstatifiedlink
#define _Included_unstatifiedlink_Unstatifiedlink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unstatifiedlink_Unstatifiedlink
 * Method:    a
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_unstatifiedlink_Unstatifiedlink_a
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
